# Generated by Django 5.0.2 on 2024-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_invoice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
