# Generated by Django 5.0.2 on 2024-03-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='car_plate_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='car_plate_source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
