# Generated by Django 5.0.2 on 2024-03-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customers_car_model_customers_car_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
