# Generated by Django 5.0.2 on 2024-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_invoice_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
