# Generated by Django 5.0.2 on 2024-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customers_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='company',
        ),
    ]
