# Generated by Django 5.0.2 on 2024-02-28 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_customers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
    ]
