# Generated by Django 5.0.2 on 2024-02-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_customers_user_alter_customers_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='warrenty',
            field=models.DateField(blank=True, null=True),
        ),
    ]
